services:
  - type: web
    name: developer-doctor-backend
    runtime: node
    region: frankfurt
    plan: free
    healthCheckPath: /health
    buildCommand: cd developer-backend && npm install
    startCommand: cd developer-backend && npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: developer-doctor-db
          property: connectionString

  - type: web
    name: developer-doctor-frontend
    runtime: static
    buildCommand: echo "static frontend"
    staticPublishPath: frontend

databases:
  - name: developer-doctor-db
    plan: free
    region: frankfurt
    postgresMajorVersion: 18
