const http=require("http");
const crypto=require("crypto");
const {Pool}=require("pg");
const pool=process.env.DATABASE_URL?new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL.includes("render.com")?{rejectUnauthorized:false}:undefined}):null;
const FREE_LIMIT=20;
async function init(){if(!pool)return;await pool.query("CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,created_at TIMESTAMPTZ DEFAULT now(),plan TEXT NOT NULL DEFAULT 'free'); CREATE TABLE IF NOT EXISTS sessions(token_hash TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,created_at TIMESTAMPTZ DEFAULT now(),expires_at TIMESTAMPTZ NOT NULL); CREATE TABLE IF NOT EXISTS analyses(id BIGSERIAL PRIMARY KEY,user_id TEXT NOT NULL,tool TEXT NOT NULL,input TEXT NOT NULL,result JSONB NOT NULL,created_at TIMESTAMPTZ DEFAULT now()); CREATE INDEX IF NOT EXISTS analyses_user_created_idx ON analyses(user_id,created_at DESC);");}
function json(res,status,b){res.writeHead(status,{"content-type":"application/json"});res.end(JSON.stringify(b));}
function hash(t){return crypto.createHash("sha256").update(t).digest("hex");}
async function user(req){const m=String(req.headers.authorization||"").match(/^Bearer\s+(.+)$/i);if(!pool||!m)return null;const r=await pool.query("SELECT s.user_id,u.plan FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=$1 AND s.expires_at>now()",[hash(m[1])]);return r.rowCount?r.rows[0]:null;}
function analyze(input){const s=String(input||""),f=[];if(/select\s+\*/i.test(s))f.push({severity:"medium",message:"SELECT * can increase I/O and coupling.",fix:"Select only required columns."});if(/like\s+['"]%/i.test(s))f.push({severity:"high",message:"Leading wildcard LIKE usually prevents a normal B-tree index.",fix:"Consider pg_trgm or another search strategy."});if(/\bjoin\b/i.test(s)&&!/\bon\b/i.test(s))f.push({severity:"high",message:"JOIN appears to have no ON condition.",fix:"Verify the join predicate."});return{score:Math.max(0,100-f.length*20),findings:f};}
async function main(){await init();const server=http.createServer(async(req,res)=>{try{const path=new URL(req.url,"http://localhost").pathname;
if(req.method==="GET"&&(path==="/"||path==="/health"))return json(res,200,{ok:true,database:!!pool,service:"developer-doctor-backend"});
if(req.method==="POST"&&path==="/api/auth/anonymous"){if(!pool)return json(res,503,{error:"Authentication requires PostgreSQL"});const id=crypto.randomUUID(),token=crypto.randomBytes(32).toString("base64url");await pool.query("INSERT INTO users(id) VALUES($1)",[id]);await pool.query("INSERT INTO sessions(token_hash,user_id,expires_at) VALUES($1,$2,now()+interval '30 days')",[hash(token),id]);return json(res,201,{token,userId:id,expiresInDays:30,plan:"free"});}
const u=await user(req);if(!u)return json(res,401,{error:"Authentication required"});
if(req.method==="GET"&&path==="/api/usage"){const r=await pool.query("SELECT count(*)::int AS analyses FROM analyses WHERE user_id=$1 AND created_at>=date_trunc('day',now())",[u.user_id]);return json(res,200,{userId:u.user_id,plan:u.plan,analyses:r.rows[0].analyses,limit:FREE_LIMIT});}
if(req.method==="GET"&&path==="/api/history"){const r=await pool.query("SELECT id,tool,result,created_at FROM analyses WHERE user_id=$1 ORDER BY created_at DESC LIMIT 50",[u.user_id]);return json(res,200,{items:r.rows});}
if(req.method==="POST"&&path==="/api/analyze"){let body="";req.on("data",c=>body+=c);req.on("end",async()=>{try{const d=JSON.parse(body||"{}"),r=await pool.query("SELECT count(*)::int AS n FROM analyses WHERE user_id=$1 AND created_at>=date_trunc('day',now())",[u.user_id]);if(r.rows[0].n>=FREE_LIMIT)return json(res,429,{error:"Daily free limit reached",limit:FREE_LIMIT});const result=analyze(d.input||d.query||"");await pool.query("INSERT INTO analyses(user_id,tool,input,result) VALUES($1,$2,$3,$4)",[u.user_id,d.tool||"developer",String(d.input||d.query||""),result]);return json(res,200,{tool:d.tool||"developer",result,remaining:FREE_LIMIT-1-r.rows[0].n});}catch(e){json(res,400,{error:"Invalid request"});}});return;}
json(res,404,{error:"Not found"});}catch(e){console.error(e);json(res,500,{error:"Internal server error"});}});server.listen(process.env.PORT||3000,"0.0.0.0");}main().catch(e=>{console.error(e);process.exit(1)});